const data = [
  {
    "Sl no": 1 ,
    "Category": "Electronics",
    "Name": "BC547 transistor",
    "Selling Price": 3,
  },
  {
    "Sl no": 2 ,
    "Category": "Electronics",
    "Name": "5 mm-LDR",
    "Selling Price": 8,
  },
  {
    "Sl no": 3 ,
    "Category": "Electronics",
    "Name": "Jumper wire male-female(pack of 10)",
    "Selling Price": 20,
  },
  {
    "Sl no": 4 ,
    "Category": "Electronics",
    "Name": "Jumper wire male-male(pack of 10)",
    "Selling Price": 20,
  },
  {
    "Sl no": 5 ,
    "Category": "Electronics",
    "Name": "Jumper wire female-female(pack of 10)",
    "Selling Price": 20,
  },
  {
    "Sl no": 6 ,
    "Category": "Electronics",
    "Name": "Servo Motor Sg 90 (360)",
    "Selling Price": 120,
  },
  {
    "Sl no": 7 ,
    "Category": "Electronics",
    "Name": "Arduino Nano",
    "Selling Price": 210,
  },
  {
    "Sl no": 8 ,
    "Category": "Electronics",
    "Name": "MAX7219 8x8 LED Dot Matrix Display Module",
    "Selling Price": 240,
  },
  {
    "Sl no": 9 ,
    "Category": "Electronics",
    "Name": "Nano 328P Expansion Adapter Breakout Board IO Shield",
    "Selling Price": 130,
  },
  {
    "Sl no": 10 ,
    "Category": "Electronics",
    "Name": "1×40 Pin 2.54mm Straight Long Female Strip Connector",
    "Selling Price": 15,
  },
  {
    "Sl no": 11 ,
    "Category": "Electronics",
    "Name": "1×40 Pin 2.54mm Straight Long Male Strip Connector",
    "Selling Price": 15,
  },
  {
    "Sl no": 12 ,
    "Category": "Electronics",
    "Name": "HC-SR04 Ultrasonic Module Distance Measuring Transducer Sensor",
    "Selling Price": 130,
  },
  {
    "Sl no": 13 ,
    "Category": "Electronics",
    "Name":
      "TP 4056 Charging Boost Lipo, Lithium Ion Battery Charging Module Board, Input Micro USB With Battery Protection Circuit",
    "Selling Price": 60,
  },
  {
    "Sl no": 14 ,
    "Category": "Electronics",
    "Name": "Mini 5V DC Power Relay SRD-5VDC-SL-C 5 Pin PCB Type ",
    "Selling Price": 25,
  },
  {
    "Sl no": 15 ,
    "Category": "Electronics",
    "Name": "KF301 2 Pin 5.08mm Pitch Plug-in Screw Terminal Block Connector",
    "Selling Price": 7,
  },
  {
    "Sl no": 16 ,
    "Category": "Electronics",
    "Name": "Arduino UNO Atmega328p",
    "Selling Price": 430,
  },
  {
    "Sl no": 17 ,
    "Category": "Electronics",
    "Name": "6 Pin DPDT Mini Push Button Self-locking Switch",
    "Selling Price": 7,
  },
  {
    "Sl no": 18 ,
    "Category": "Electronics",
    "Name": "400 Points Half Size Solderless Breadboard",
    "Selling Price": 60,
  },
  {
    "Sl no": 19 ,
    "Category": "Electronics",
    "Name": "Single Pin Wire",
    "Selling Price": 15,
  },
  {
    "Sl no": 20 ,
    "Category": "Electronics",
    "Name": "Shyno 5V 1A Charger for Arduino UNO",
    "Selling Price": 140,
  },
  {
    "Sl no": 21 ,
    "Category": "Electronics",
    "Name": "B type Cable for Arduino UNO",
    "Selling Price": 40,
  },
  {
    "Sl no": 22 ,
    "Category": "Electronics",
    "Name": "9v Battery",
    "Selling Price": 25,
  },
  {
    "Sl no": 23 ,
    "Category": "Electronics",
    "Name": "Veroboard Dotted",
    "Selling Price": 48,
  },
  {
    "Sl no": 24 ,
    "Category": "Electronics",
    "Name": "Piezo Buzzer",
    "Selling Price": 12,
  },
  {
    "Sl no": 25 ,
    "Category": "Electronics",
    "Name": "CPU Jack",
    "Selling Price": 5,
  },
  {
    "Sl no": 26 ,
    "Category": "Electronics",
    "Name": "2AA Battery Case",
    "Selling Price": 25,
  },
  {
    "Sl no": 27 ,
    "Category": "Electronics",
    "Name": "GL12 840 Points Solderless Breadboard",
    "Selling Price": 100,
  },
  {
    "Sl no": 28 ,
    "Category": "Electronics",
    "Name": "Otto Classic complete kit",
    "Selling Price": 1999,
  },
  {
    "Sl no": 29 ,
    "Category": "Electronics",
    "Name": "Otto Humanoid complete kit",
    "Selling Price": 2499,
  },
  {
    "Sl no": 30 ,
    "Category": "Electronics",
    "Name": "Otto Classic 3d parts",
    "Selling Price": 379,
  },
  {
    "Sl no": 31 ,
    "Category": "Electronics",
    "Name": "Otto Humanoid 3d parts",
    "Selling Price": 419,
  },
  {
    "Sl no": 32 ,
    "Category": "Electronics",
    "Name": "Touch Sensor",
    "Selling Price": 60,
  },
];

export { data };
